# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'git_custom_gui_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(630, 0, 391, 731))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.console_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.console_input.setMinimumSize(QtCore.QSize(279, 0))
        self.console_input.setStyleSheet("font: 8pt \"Lucida Console\";\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "background-color: rgb(0, 0, 0);\n"
                                         "")
        self.console_input.setText("")
        self.console_input.setObjectName("console_input")
        self.gridLayout.addWidget(self.console_input, 1, 0, 1, 1)
        self.console_output = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.console_output.setMinimumSize(QtCore.QSize(0, 454))
        self.console_output.setStyleSheet("font: 8pt \"Lucida Console\";\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "background-color: rgb(0, 0, 0);\n"
                                          "")
        self.console_output.setReadOnly(True)
        self.console_output.setPlainText("")
        self.console_output.setObjectName("console_output")
        self.gridLayout.addWidget(self.console_output, 2, 0, 1, 1)
        self.label_console_manual = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_console_manual.setStyleSheet("font: 9pt \"Lucida Console\";\n"
                                                "color: rgb(255, 255, 255);\n"
                                                "background-color: rgb(0, 0, 0);\n"
                                                "")
        self.label_console_manual.setAlignment(QtCore.Qt.AlignCenter)
        self.label_console_manual.setObjectName("label_console_manual")
        self.gridLayout.addWidget(self.label_console_manual, 0, 0, 1, 1)
        self.commitMessege = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.commitMessege.setGeometry(QtCore.QRect(180, 460, 451, 271))
        self.commitMessege.setObjectName("commitMessege")
        self.label_commit_messege = QtWidgets.QLabel(self.centralwidget)
        self.label_commit_messege.setGeometry(QtCore.QRect(180, 440, 261, 20))
        self.label_commit_messege.setObjectName("label_commit_messege")
        self.commitButton = QtWidgets.QPushButton(self.centralwidget)
        self.commitButton.setGeometry(QtCore.QRect(0, 459, 181, 31))
        self.commitButton.setMinimumSize(QtCore.QSize(0, 0))
        self.commitButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.commitButton.setObjectName("commitButton")
        self.commit_all = QtWidgets.QRadioButton(self.centralwidget)
        self.commit_all.setGeometry(QtCore.QRect(0, 490, 71, 17))
        self.commit_all.setMinimumSize(QtCore.QSize(0, 0))
        self.commit_all.setChecked(True)
        self.commit_all.setObjectName("commit_all")
        self.commit_one_file = QtWidgets.QRadioButton(self.centralwidget)
        self.commit_one_file.setGeometry(QtCore.QRect(0, 510, 101, 17))
        self.commit_one_file.setMinimumSize(QtCore.QSize(0, 0))
        self.commit_one_file.setMaximumSize(QtCore.QSize(150, 150))
        self.commit_one_file.setObjectName("commit_one_file")
        self.label_commit_one_file = QtWidgets.QLabel(self.centralwidget)
        self.label_commit_one_file.setEnabled(True)
        self.label_commit_one_file.setGeometry(QtCore.QRect(0, 530, 91, 20))
        self.label_commit_one_file.setMinimumSize(QtCore.QSize(0, 0))
        self.label_commit_one_file.setMaximumSize(QtCore.QSize(150, 25))
        self.label_commit_one_file.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_commit_one_file.setObjectName("label_commit_one_file")
        self.commit_one_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.commit_one_file_name.setEnabled(True)
        self.commit_one_file_name.setGeometry(QtCore.QRect(0, 550, 181, 20))
        self.commit_one_file_name.setMinimumSize(QtCore.QSize(0, 20))
        self.commit_one_file_name.setClearButtonEnabled(False)
        self.commit_one_file_name.setObjectName("commit_one_file_name")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(180, 40, 451, 401))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 20, 21, 20))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 40, 181, 20))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 20, 91, 21))
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.current_branch = QtWidgets.QLabel(self.centralwidget)
        self.current_branch.setGeometry(QtCore.QRect(0, 0, 410, 16))
        self.current_branch.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.current_branch.setObjectName("current_branch")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 0, 131, 31))
        self.pushButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuRepository = QtWidgets.QMenu(self.menubar)
        self.menuRepository.setObjectName("menuRepository")
        self.menuBranch = QtWidgets.QMenu(self.menubar)
        self.menuBranch.setObjectName("menuBranch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionCheckout = QtWidgets.QAction(MainWindow)
        self.actionCheckout.setObjectName("actionCheckout")
        self.actionRename = QtWidgets.QAction(MainWindow)
        self.actionRename.setObjectName("actionRename")
        self.actionNew_commit = QtWidgets.QAction(MainWindow)
        self.actionNew_commit.setObjectName("actionNew_commit")
        self.actionAmmend_last_commit = QtWidgets.QAction(MainWindow)
        self.actionAmmend_last_commit.setObjectName("actionAmmend_last_commit")
        self.actionExplore_Working_Directory = QtWidgets.QAction(MainWindow)
        self.actionExplore_Working_Directory.setObjectName("actionExplore_Working_Directory")
        self.actionRename_2 = QtWidgets.QAction(MainWindow)
        self.actionRename_2.setObjectName("actionRename_2")
        self.actionView_Log = QtWidgets.QAction(MainWindow)
        self.actionView_Log.setObjectName("actionView_Log")
        self.actionSelect_Working_Directory = QtWidgets.QAction(MainWindow)
        self.actionSelect_Working_Directory.setObjectName("actionSelect_Working_Directory")
        self.menuRepository.addAction(self.actionSelect_Working_Directory)
        self.menuRepository.addAction(self.actionExplore_Working_Directory)
        self.menuRepository.addAction(self.actionView_Log)
        self.menuBranch.addAction(self.actionCreate)
        self.menuBranch.addAction(self.actionCheckout)
        self.menuBranch.addAction(self.actionRename)
        self.menubar.addAction(self.menuRepository.menuAction())
        self.menubar.addAction(self.menuBranch.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_console_manual.setText(_translate("MainWindow", "Manual command input"))
        self.label_commit_messege.setText(_translate("MainWindow", "Commit messege:"))
        self.commitButton.setText(_translate("MainWindow", "Commit"))
        self.commit_all.setText(_translate("MainWindow", "Commit All"))
        self.commit_one_file.setText(_translate("MainWindow", "Commit One File"))
        self.label_commit_one_file.setText(_translate("MainWindow", "File name:"))
        self.label_3.setText(_translate("MainWindow", "File:"))
        self.label_2.setText(_translate("MainWindow", "Tracked Files:"))
        self.current_branch.setText(_translate("MainWindow", "Current Branch:"))
        self.pushButton.setText(_translate("MainWindow", "Refresh ↺"))
        self.menuRepository.setTitle(_translate("MainWindow", "Repository"))
        self.menuBranch.setTitle(_translate("MainWindow", "Branch"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionCheckout.setText(_translate("MainWindow", "Checkout"))
        self.actionRename.setText(_translate("MainWindow", "Rename Current"))
        self.actionNew_commit.setText(_translate("MainWindow", "New commit"))
        self.actionAmmend_last_commit.setText(_translate("MainWindow", "Amend Last Commit"))
        self.actionExplore_Working_Directory.setText(_translate("MainWindow", "Explore Working Directory"))
        self.actionRename_2.setText(_translate("MainWindow", "Rename"))
        self.actionView_Log.setText(_translate("MainWindow", "View Log"))
        self.actionSelect_Working_Directory.setText(_translate("MainWindow", "Select Working Directory"))
